name: Test
on:
  push:
    branches-ignore:
      - "master"
    paths-ignore:
      - "website"
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    name: "Test"
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            task: build:linux-all
          - os: macos-latest
            name: mac
            task: build:mac-all
          - os: windows-latest
            name: win
            task: build:win-all
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Cache
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: |
          yarn install --immutable --network-timeout 120000
      - name: Build
        run: |
          yarn build
          yarn lerna run ${{ matrix.task }} --stream
      - name: Build Snap
        if: matrix.name == 'linux'
        run: |
          sudo snap install snapcraft --classic
          yarn lerna run build:snap --stream
      - uses: actions/upload-artifact@v3
        if: matrix.name == 'win'
        with:
          name: built-app-${{ matrix.name }}-all
          path: |
            app/main/dist/Pomatez*[!ai]*.exe
      - uses: actions/upload-artifact@v3
        with:
          name: built-app-${{ matrix.name }}-ia32
          path: |
            app/main/dist/Pomatez*ia32*.*
      - uses: actions/upload-artifact@v3
        with:
          name: built-app-${{ matrix.name }}-x64
          path: |
            app/main/dist/Pomatez*x64*.*
            app/main/dist/Pomatez*x86_64*.*
            app/main/dist/Pomatez*amd64*.*
      - uses: actions/upload-artifact@v3
        with:
          name: built-app-${{ matrix.name }}-arm64
          path: |
            app/main/dist/Pomatez*arm64*.*
            app/main/dist/Pomatez*aarch64*.*
      - uses: actions/upload-artifact@v3
        with:
          name: built-app-${{ matrix.name }}-armv7l
          path: |
            app/main/dist/Pomatez*armv7l*.*
      - uses: actions/upload-artifact@v3
        with:
          name: built-app-${{ matrix.name }}-autoupdater
          path: |
            app/main/dist/latest*
